### ISSUE TITLE
Validation should be done within the form itself

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/free4all#14]
Depending on what was not filled in, sometimes might throw an error in the console, or other times Bert will popup notify about validation errors.

Should perform validation right when `onsubmit` event is fired, and highlight the errored fields. See `imports/modules/login.js` for an example of validation using jquery-validation,

**Comment by leonmak** [comment]
For now I've used hidden fields to trigger invalidation

**Comment by irvinlim** [comment]
For now, there aren't error messages to prompt the user, just a disabled submit button. You can refer to the settings page to see how I've done it using Formsy as well.

Either ways, this is no longer a huge issue since invalid forms can't be submitted, but it would be nice to have error messages.
