### ISSUE TITLE
Edit giveaway dialog should show recurring switch, have similar behaviour

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/free4all#20]
The Edit Giveaway dialog needs to have the same behaviour for recurring events. Otherwise, users can make a single giveaway span across multiple days (non-recurring).

Steps to reproduce:
1. Create a non-recurring giveaway.
2. Go to dashboard and edit the same giveaway.
3. Modify End Date or Start Date to another date and save.
4. The single giveaway will now span across multiple dates.

I believe you didn't intend for giveaways to be able to be spanned across multiple days right?

Furthermore, I think the dialog actions (Edit Group, Delete Group) should only be shown for recurring events.

**Comment by irvinlim** [comment]
The behaviour for different start and end date for non-recurring giveaways is still not settled. Do you think we should allow giveaways to span across more than 1 day? Because if so, the recurring switch will be ambiguous, since it will change the giveaway from spanning across multiple days to multiple giveaways recurring daily.

**Comment by irvinlim** [comment]
Also, the Delete and Delete Group buttons are misleading for non-recurring giveaways.

**Comment by leonmak** [comment]
Resolved as #41 removes recurring functionality
