### ISSUE TITLE
Identify memory optimisations for slower mobiles

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/free4all#23]
It's currently very laggy on my phone (Chrome on Galaxy Note 4).

**Comment by leonmak** [comment]
the moveend event seems to be the problem, changed to dragend and zoomend

**Comment by irvinlim** [comment]
Is this fixed? Maybe can deploy on modulus to test on our phones.

**Comment by leonmak** [comment]
Yup deployed and seems to be smooth on my phone

**Comment by irvinlim** [comment]
Same here, pretty smooth now
