### ISSUE TITLE
Map tile settings

### ISSUE THREAD

**Issue by leonmak** [irvinlim/free4all#24]
The use case would be for a specific public event giveaway (eg. NUS SLF, Marathons):
The organiser may want to show only the giveaways at their event, and customize the map colors/style to their event.

Mapbox provides a leaflet url for the style, so this can be tagged to the username, as it's unique.
Users can just input the url, and get people to follow them.
Another route can then be used for logged in users to choose from which user(s) they want to show the giveaways. The map style would then be the first one they selected, if we allow multiple selections

'Followers' can then be part of the analytics in addition to ratings

**Comment by leonmak** [comment]
wrt #25, we can put the tile settings under the communities too

**Comment by irvinlim** [comment]
Issue closed, dup of #25.
