### ISSUE TITLE
Communities

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/free4all#25]
**Landing page**
- New visitors: NUS NTU SMU (etc), on click will set a cookie
- Returning visitors: Center map on community set in cookie
- Logged in users: Get setting in user profile

**Other things**
- Add to user and giveaway schemas
- Add menu item to Change Community

**Comment by leonmak** [comment]
instead of [cookies](http://info.meteor.com/blog/session-cookies), I'll try this pkg for [persistent sessions](https://github.com/okgrow/meteor-persistent-session)

**Comment by irvinlim** [comment]
Nice job, however I think communityId should be part of the Users schema? Are we planning to allow a User to be part of more than 1 community?

Also, I think the publication for giveaways should be limited to the community also right?

Just some feedback.

**Comment by irvinlim** [comment]
After testing a bit more, I think the behaviour we wanted was:

**Home community**
- On the landing page, instead of just checking only the Session variable, if user is logged in, check in user profile first for home community.
- On login, if Session var is set and home community is not set, can copy the value over to user profile.

**Giveaways**
- Each giveaway is supposed to have a communityId field also, right? So that NTU giveaways won't appear in NUS students' timelines, for example.
- If you join multiple communities, then it might be a problem to add giveaways. Hence, we need to add an additional field for the user to choose the community (only choose from those he has joined).

**Misc**
- Instead of hardcoding the coordinates in `index.js`, can just refer to the data in the community collection.
- I don't think we should allow the public to add communities, but maybe provide a form for them to request communities? (not important as of now)

**Comment by leonmak** [comment]
For giveaways, I'll change the community Ids array to be in the giveaways instead of the users.

**Comment by irvinlim** [comment]
@leonmak Could I take a look at the updated Giveaway schema you are planning to use to implement the community IDs array? 

Will the new giveaway be created as multiple copies for each community, or a single document that will appear in each relevant community? I'm assuming the latter. If so, then I suppose the field will be an array of community IDs that they should appear in, is that correct?

The excludedIds array should not be used, because:

1. If the user joins a new community that Giveaway doesn't get excluded (should not include it when in doubt)
2. MongoDB will have to perform 2 queries: the first to fetch a list of userIds in a community, and the second to fetch all giveaways that contain any of the userIds.

Instead, if we use a communityIds array field to specify the community the giveaway should be in explicitly, then we can do it in one query with just:
```
Giveaways.findOne({ communityIds: communityId });
```

The UI to choose the community in the form can still be include all communities by default, but the schema should not store it as excludedIds.

By the way, is it possible to select communities using a dropdown select (similar to GitHub's select assignees dropdown)?

**Comment by leonmak** [comment]
yea ok, I think include is more intuitive, anyway include/exclude is still one query to the giveaways

**Comment by irvinlim** [comment]
@leonmak You should also make the behaviour of the Set Home button such that it will make the user join the community if he isn't already in.

Same thing when the user logs in for the first time and homeCommunityId isn't set.

**Comment by leonmak** [comment]
yea I did that for the first time log in one alr

**Comment by irvinlim** [comment]
Just a question, why is communityIds not in profile but homeCommunityId, etc are in user profile fields?

Also, why can't we just have homeCommunityId, without homeLocation and homeZoom? Those can obtain from Communities schema right?

**Comment by irvinlim** [comment]
Also, you are changing the communities view to be such that you will find giveaways where `communityIds` contains the community ID right? Not the current way where you find where `userId` is in an array of userIds which are in a certain community?

**Comment by irvinlim** [comment]
FYI, I updated the methods in 894c9cf to be less redundant, more DRY. Behaviour remains the same.

**Comment by leonmak** [comment]
1. No particular reason for communityIds, I thought you wanted the homecommunity Id for the profile right? Put the location and zoom so I didn't need to do another query to communities collection. 
2. Yea.
3. Ok

**Comment by leonmak** [comment]
For home community session, I haven't done for local sign up, only for social sign up

**Comment by irvinlim** [comment]
Ok. Nice job, I think it's kind of done already.

I presume we still have to do the publication to publish only giveaways where includedIds contains any of the user's communities right? 

Also, there is a problem if let's say you are in multiple communities, want to add a giveaway to a community that is not your home community (e.g. want to add to SMU), then the map will be centered on NUS, which is very far from SMU. Not sure how to solve that.

**Comment by irvinlim** [comment]
Actually, the multiple communities thing is a small problem. I don't think there will be any giveaways such that it is held in NUS but belongs to any other community as well; this is just for future use cases if we expand communities to be more than just universities.
