### ISSUE TITLE
Need URL route to edit a specific giveaway

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/free4all#31]
For example, I want a direct link from the giveaway page to the edit giveaway form.

I think it is simple enough, to get `this.props.params.id` in the component to pass it to the component state, to select giveaway and open the modal using `componentWillReceiveProps` or something.

**Comment by leonmak** [comment]
Resolved

**Comment by irvinlim** [comment]
FYI, I made the URL in the address bar react to the state as well.
